CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    description text
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    borrowed BOOLEAN, 
    userId INTEGER REFERENCES users(id)
);

-- list al tables
\dt

-- list all data in users table
SELECT * FROM users;

-- INSERT TEST DATA FOR users
INSERT INTO users(name, description)
    VALUES ('Carlos Menem', 'Cliente VIP');


-- INSERT TEST DATA FOR books
INSERT INTO books(name, borrowed, userId)
    VALUES('El Alquimista - Paulo Cohelo', true, 1);

select * from books;

select * from books where userId = 1;